### ISSUE TITLE
window.resizeTo in webview !

### ISSUE THREAD

**Issue by IllusionPerdu** [sopium/webview2#1]
Hello

When we execute `window.resizeTo(width, height)` in the webview the main window does not change size (with the example).

**Comment by sopium** [comment]
You need to resize the window in rust (`set_inner_size` if you use `winit`, or `SetWindowPos`).

**Comment by sopium** [comment]
I don't think there's anything I can do about this. And the workaround is simple and straightforward. So I'm going to close this issue.
