### ISSUE TITLE
Feature request: put_DefaultBackgroundColor

### ISSUE THREAD

**Issue by wusyong** [sopium/webview2#10]
First of all, thanksfor your work! I'm very glad to find this crate.
The interface is super easy to use and pretty ergonomic!
I have a requirement that need to construct a window with transparent background.
And looks like the upstream [updated this feature](https://github.com/MicrosoftEdge/WebView2Feedback/issues/328#issuecomment-770137759) recently.
Could we also update to it?
I'm willing to help. Just maybe need to know how to run the idl2rs binary.
It seems all interfaces are generated from that tool?

**Comment by sopium** [comment]
I tried it and it seems to work:

https://github.com/sopium/webview2/commit/ca5dbd7959b030ed574b548457c6c16246284a7d#diff-2dc46f450fd671c92abaecb89b2b6842af16747d8a5de2082ae4663c07697b88R136-R153

But the SDK version is a prerelease and this feature only works with Edge dev/canary. I'm inclined to wait for a bit more stabilization before properly supporting it.

**Comment by sopium** [comment]
BTW you can see how idl2rs is run here:

https://github.com/sopium/webview2/blob/4bd814aca6fe018655c8a0bf8cbda591e9d1b5b8/.github/workflows/ci.yml#L138-L141

**Comment by wusyong** [comment]
Thank you so much! It can definitely wait. 
I just need to make sure if it's possible to do so.
I tried to update today but stuck on how to use those continuation iterfaces.

The idl2rs crate is really amazing too!
It actually just took me a few minutes to get familiar with it.

**Comment by wusyong** [comment]
@sopium Thank you again for the help! Just tested it and it works perfectly!
Btw, do you plan to publish a new version to crates.io? Because in the release of tauri, we need to publish to there too.

**Comment by sopium** [comment]
Just released v0.1.0.
