### ISSUE TITLE
Needs a way to set background color for webview for WPF

### ISSUE THREAD

**Issue by musictopia2** [sopium/webview2#14]
Currently, there is no way of being able to set the background color.  This means if I have other content in WPF that has the expected color, even if I set in the html, it still flickers.

**Comment by sopium** [comment]
Does this work for you?

https://github.com/sopium/webview2/blob/fac3796ca9699de61ad5d767df3b5faeecdb5e3a/examples/background_color.rs#L164-L174

**Comment by musictopia2** [comment]
I wanted to be able to set to a color that shows from intellisense like Navy, Black, Aqua, etc.
Also, I am doing from c#, not c++ as well.

**Comment by sopium** [comment]
I'm a bit confused. This repository contains a webview2 binding for rust. Are you sure you are using this from c#?

**Comment by musictopia2** [comment]
There is a wrapper from C#.  That is why the title says for WPF.  The namespace I am using is Microsoft.Web.WebView2.Wpf.WebView2

**Comment by sopium** [comment]
Do you mean the official WPF wrapper? Then you should probably report the issue to https://github.com/MicrosoftEdge/WebView2Feedback

**Comment by musictopia2** [comment]
I did not know that.  Thanks for letting me know.

**Comment by sopium** [comment]
No problem.
