### ISSUE TITLE
Where can I find the WebView2Loader.dll file?

### ISSUE THREAD

**Issue by TabulateJarl8** [sopium/webview2#20]
Hey, I was wondering if there was some trustworthy place where I could get the `WebView2Loader.dll` file. I would like to package it with the binary for my project (I'm cross compiling from Linux to Windows), but the only place I can find it is [here](https://www.dll-files.com/webview2loader.dll.html). Thanks for the help

**Comment by blckngm** [comment]
It's in the nuget package: https://www.nuget.org/api/v2/package/Microsoft.Web.WebView2/1.0.1108.44

There is also a copy in this repo: https://github.com/sopium/webview2/raw/master/webview2-sys/Microsoft.Web.WebView2.1.0.961.33/build/native/

**Comment by TabulateJarl8** [comment]
Thanks!
