### ISSUE TITLE
I have find this !

### ISSUE THREAD

**Issue by IllusionPerdu** [sopium/webview2#4]
Hello,

To avoid writing the embedded dll in disk you can probably use this:
 * https://github.com/fancycode/MemoryModule
And the rust bindings:
 * https://github.com/indygreg/rs-memory-module-sys

Sorry for my bad english !

**Comment by sopium** [comment]
Oh I have heard about this, didn't know there is rust bindings too. Definitely worth trying.

**Comment by IllusionPerdu** [comment]
I have testing to use it in #5 
It's work but you can probably improve the code ;)
