### ISSUE TITLE
Trouble run examples on Windows

### ISSUE THREAD

**Issue by sirfredrick** [sopium/webview2#6]
Is this project able to run currently on Windows 10? I finally got it to build with `cargo build` using `x86_64-pc-windows-msvc` but `cargo run` does nothing. Am I supposed to build my own app first or is there a way to get the built in examples to work?

I would love to help with this project if that is possible. Let me know what I could work on!

**Comment by sopium** [comment]
You need to specify the example to run:
https://stackoverflow.com/a/54470945

**Comment by sirfredrick** [comment]
Thanks that helped! I'll get started implementing my app!
